### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by fa7ad** [optimisme/gnome-shell-simple-dock#2]
Is there any possibility that you might be able to implement some sort of indicator to show the number of running instances of a process. 
Also, like the "dash to dock" extension, can you implement a way to cycle through the windows, instead of just minimizing them when one clicks on a running app's icon.

Really loved the extension,
Look forward to more stuff from you, TIA

**Comment by optimisme** [comment]
Hi, 

The last 'github' version:

1) The indicator is shown by 'gnome' itself, i am not sure about changing the default style.
2) Allows cycling windows scrolling over the icon.

I hope it helps.

**Comment by marcvangend** [comment]
Thanks! The scroll-to-cycle works nice. The indicator works just like in the default Gnome dash, as you say. However that indicator does not make a difference between one or multiple windows, which (if I understand correctly) is what fa7ad meant to ask for in his original post.
