### ISSUE TITLE
git version for gnome-shell 3.10 and 3.12 is missing in metadata.json

### ISSUE THREAD

**Issue by fastrizwaan** [optimisme/gnome-shell-simple-dock#4]
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Bottom dock\n\nFeaturing:\n- Intelligent auto hide.\n- Minimize focused application.\n- Drag and drop favorites. \n- Disable message tray (Optional). \n- Move notifications to top (Optional). \n- Adjust icon sizes (Optional)\n\nThanks to Ozon OS dock, Panel OSD, Disable message tray", 
  "name": "Simple Dock", 
  "settings-schema": "org.gnome.shell.extensions.simple-dock", 
  "shell-version": [
    "3.10", "3.12", "3.14"
  ], 
  "url": "https://github.com/optimisme/gnome-shell-simple-dock", 
  "uuid": "simple-dock@nothing.org", 
  "version": 35
}

**Comment by optimisme** [comment]
The last versio does not work on 3.10 and 3.12, so it is not missing does not work. To install it on these gnome versions it is better to use the source from "gnome extensions site"
