### ISSUE TITLE
This must be in Fedora Repos

### ISSUE THREAD

**Issue by williamjmorenor** [optimisme/gnome-shell-simple-dock#5]
Hello

Great add for the Gnome Shell desktop, I will try to package it for Fedora.

**Comment by williamjmorenor** [comment]
Hello

I am working in the SPEC file to include this extensión in the Fedora Repositori, can you please confirme the license of your project, so I can be sure this can be in Fedora repo o RPM Fusion repo

Regards

**Comment by optimisme** [comment]
Hi William,

Feel free to get my source and modify/distribute it if you like.

I originally used the source of other extensions, licensed as:

Ozon os dock: GPL v3
Panel OSD: GPL v3
Disable message tray: GPL v2

Keep in mind that my extension has some known bugs, and I will try to fix
those as soon as I have more knowledge and time.

Thanks,

Albert

**Comment by williamjmorenor** [comment]
Packaged

https://admin.fedoraproject.org/pkgdb/package/gnome-shell-extension-simple-dock/
