### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by cyn1c** [optimisme/gnome-shell-simple-dock#8]
After introducing transparency the theming support seems to be broken. I use the Numix Frost theme and bevor the last update the dock used this theme. After the update it seems to me that the dock uses the gnome-shell standard theme which does not match the rest of the desktop theme. Are there any plans to fix this issue?
otherwise i like the extension very much, thanks for it!

**Comment by optimisme** [comment]
Hi, thanks for the bug report. I will look why your theme is not properly
shown, and I will try to fix it. :)

**Comment by optimisme** [comment]
Hi Cyn1c,

Please update the dock from '
https://extensions.gnome.org/extension/815/simple-dock/', your background
color problem should be fixed.

Thanks

**Comment by cyn1c** [comment]
Excellent job. Everthing works again as it did bevor! 
Thanks for the quick fix!
